apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hasher
  name: hasher
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 80
  selector:
    io.kompose.service: hasher
status:
  loadBalancer: {}
